# Generated by Django 3.2.16 on 2022-12-25 10:25

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ticket.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(default='dj', max_length=255)),
                ('updated_at', models.DateField(auto_now=True)),
                ('updated_by', models.CharField(default='dj', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('Agent', 'Agent'), ('Subadmin', 'Subadmin'), ('User', 'User')], max_length=20)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('status', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', ticket.managers.Usermanager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(default='dj', max_length=255)),
                ('updated_at', models.DateField(auto_now=True)),
                ('updated_by', models.CharField(default='dj', max_length=255)),
                ('mobile', models.CharField(max_length=10)),
                ('assets', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Emergency', 'Emergency')], max_length=20)),
                ('serial_no', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)])),
                ('model_no', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)])),
                ('ticketstatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Ready-to-dispatch', 'Ready-to-dispatch'), ('Dispatched', 'Dispatched'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('assigned_to', models.ForeignKey(limit_choices_to=models.Q(('role', 'Agent')), on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to=models.Q(('role', 'User')), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
